### ISSUE TITLE
Configuration discussion

### ISSUE THREAD

**Issue by bluejekyll** [bluejekyll/vermilion#1]
Some principles:

- We don't want a new DSL, choose something off the shelf, KISS
  - Choose a simple and clear config language, TOML?
- We want to lean on declarative configuration where it makes sense
- For imperative support, just rely on external scripting languages being called.
  - Does this expose potential issues for privileged execution?
- Let's make it obvious what all dependencies are in a system
  - Discovery of services should be easy
  - Services should register the types of services they offer
  - Service types are probably mostly mutually exclusive, do we support service types that can be provided by more than one tool?

**Comment by bluejekyll** [comment]
example TOML, let's assume this lives in a directory: `/etc/verm.rc/named/Verm.toml`

All config loads would assume default path in that directory, so start executables would be siblings of the toml. All of them can be optional, except for the toml file. We should provide a CLI to create a new rc directory.

Should we allow a naked toml as well: `/etc/verm.rc/named.toml`?

```toml
name = "Trust DNS"
provides = "dns"

# command line arguments, etc.
#   perhaps this is rooted in the config path of like /etc/vermilion.rc
#   aka start?
[command]
path = "named"
arguments = ["--debug", "--config_path=/etc/named"]

# defaults to look for stop executable in directory
[stop]
path = "stop"

# we should bake smoke tests in directly to test the service after it starts (non-destructive obviously).
[smoke_test]
path = "/test/bin/host"
# ...

# Are there default dependencies? or globs? like `posix = ["network", "fs", ...]`
[dependencies]
network = [version = "API version?", optional = "false"]
fs = "*"
```
obviously not fully fleshed out...
